### ISSUE TITLE
[DEMO 1] Admin - Vista QUIZ/Crear nuevo Quiz

### ISSUE THREAD

**Issue by ThamairyGonzalez** [Programa-TrainIT-Ar/challenge-fe#11]
El Diseñador generará en Media/Alta las Vistas asociadas a la funcionalidad crear nuevo Quizz, y colocará la tag Ready a aquellas que puedas comenzar a codearse

**Comment by OskrAraujo** [comment]
Vistas y frames creados y ready for dev.
