### ISSUE TITLE
[DEMO 1] Administrador - Vista QUIZ/ Ver Todos los Quiz

### ISSUE THREAD

**Issue by ThamairyGonzalez** [Programa-TrainIT-Ar/challenge-fe#13]
El Diseñador generará en Media/Alta las Vistas asociadas a la funcionalidad  Ver Todos los Quiz, y colocará la tag Ready a aquellas que puedas comenzar a codearse

**Comment by OskrAraujo** [comment]
Vista de los quiz finalizada, estados de los Frames actualizados en el figma
