### ISSUE TITLE
[ADM-TOD-T0007] Falla visual, alteración del menú al abrir la pestaña Editar

### ISSUE THREAD

**Issue by tomiiv** [Programa-TrainIT-Ar/challenge-fe#36]
**Precondiciones:**
Login exitoso / Rol requerido: Administrador.

**Pasos:**
1. Entrar a la página Programa de Candidatos TrainIT y loguearse como Admin (URL: https://challenge-fe-testing.netlify.app/).
2. Estar o apretar en Gestión Quiz, localizada en el margen izquierdo, y luego la pestaña Todos.
3. Apretar en el botón de Editar, localizado en la columna Acciones y representado con un lápiz, sobre el quiz deseado.
4. Apretar en la pestaña Todos o Nuevo, y luego volver a apretar en la pestaña Editar

**Resultado Esperado:** Se espera poder volver a la pestaña Editar para seguir con editando el Quiz deseado.

**Resultado Obtenido:** Al seguir con los pasos, se puede visualizar que la pantalla de altera de manera abrupta. Esto deduzo que se debe a que, si bien al estar con la pestaña Editar abierta y al cambiar a Todos o Nuevo esta se cierra, al volver a apretar en la pestaña anterior que sería Editar, la otra no se cierra, provocando que haya dos pestañas abiertas al mismo tiempo.

**Entorno:**
Sistema operativo: Windows 11 Home
Navegador web o móvil: Versión web
Fecha y hora: 30/11 03:05pm

**Navegador o Dispositivo:** Google Chrome

**Tipo:** Falla

**Prioridad y Severidad:**
Prioridad: (Asignada por la líder QA)
Severidad: Alta

**Mejoras o Sugerencias:** En el momento de apretar en otra pestaña que la que estaba activa anteriormente se cierre, o directamente que en el momento de abandonar la pestaña Editar que esta se elimine del tablero. Además, al cambiar de pestaña se pierden todos los datos ingresados previamente, por lo que pierde sentido. Esta solo se irá si se apreta en el botón volver al listado.

**Evidencias:**
![Todos, Editar 22024-10-30 030031](https://github.com/user-attachments/assets/46270db5-730b-4169-a46a-88f0b8f4afab)
https://drive.google.com/file/d/1GYuxbngwtCLmJgqlSrVVu6nZJRjk3ziV/view?usp=sharing

**Tester a Cargo:** Tomás Soto

**Comment by jesusdanielGIT** [comment]
se modifico la funcionalidad de mostrar pestañas para evitar sobre posicionamiento.
