### ISSUE TITLE
[ADM-TOD-T0008] Falta de funcionalidad de los botones dentro de la pestaña Editar

### ISSUE THREAD

**Issue by tomiiv** [Programa-TrainIT-Ar/challenge-fe#37]
**Precondiciones:**
Login exitoso / Rol requerido: Administrador.

**Pasos:**
1. Entrar a la página Programa de Candidatos TrainIT y loguearse como Admin (URL: https://challenge-fe-testing.netlify.app/).
2. Estar o apretar en Gestión Quiz, localizada en el margen izquierdo, y luego la pestaña Todos.
3. Apretar en el botón de Editar, localizado en la columna Acciones y representado con un lápiz, sobre el quiz deseado.
4. Llenar los datos y apretar en el botón Guardar o Siguiente.

**Resultado Obtenido:** 

**Entorno:**
Sistema operativo: Windows 11 Home
Navegador web o móvil: Versión web
Fecha y hora: 30/11 03:39pm

**Navegador o Dispositivo:** Google Chrome

**Tipo:** Defecto

**Prioridad y Severidad:**
Prioridad: (Asignada por la líder QA)
Severidad: Alta

**Mejoras o Sugerencias:** Terminar la funcionalidad de Editar Quiz

**Evidencias:**
![Editar Quiz, botones 2024-10-30 032420](https://github.com/user-attachments/assets/8f4d3dba-67b3-4871-9b55-0bd6e1e7505f)
https://drive.google.com/file/d/1hGZKJKLB6sl5lrqGFksnz_Uqf18fJ5Mz/view?usp=sharing

**Tester a Cargo:** Tomás Soto

**Comment by ThamairyGonzalez** [comment]
Adicional a Bugs referidos en la descripcion , se debe incorporar los inputs que habiliten edicion de nombre y descripcion como en la imagen de prototipo referenciada a continuacion ![Image](https://github.com/user-attachments/assets/7931b38b-7818-41d9-a6bd-097cfebd958a)
