### ISSUE TITLE
[ADM-PANTALLA NUEVO-002] BUG | Inconsistencias tipográficas de labels dropdown Seniority.

### ISSUE THREAD

**Issue by Kreinstin** [Programa-TrainIT-Ar/challenge-fe#39]
**Pre-condiciones:**
Usuario autenticado con acceso a la pantalla "Nuevo".
**Pasos para reproducir:**
Ingresar a la pantalla **"Nuevo".**
Revisar las opciones disponibles en los filtros "Módulo", "Célula" y "Seniority/Nivel".
**Resultado esperado:**
Los filtros "Módulo", "Célula" y "Seniority/Nivel" deben contener las opciones correctas, con una escritura y formato adecuados. 
Resultado obtenido:
Los filtros contienen opciones incorrectas y presentan errores de escritura y formato.

**Entorno:**
Navegador: Google Chrome

**Tipo de error:** Funcional

**Fecha de prueba:** 1 Noviembre 2024

Prioridad: 
Severidad: Media

**Mejoras o sugerencias:**
Corregir las opciones de los filtros para asegurar que sean las adecuadas.
Revisar y ajustar la escritura y el formato de los filtros para garantizar la consistencia y legibilidad, también la manera en la que se ordenan. 

![Mayusculas](https://github.com/user-attachments/assets/051c9eea-4f98-4ac7-a9d2-e964ed84e91c)

**Comment by Salazarignacio** [comment]
Bug solucionado
